import {
  ActivityEvent,
  AppNotification,
  ChatMessage,
  ChatRoom,
  DemoUser,
  Donation,
} from './types';

// Stable timestamps so SSR/CSR render identically.
const now = new Date('2026-04-11T11:30:00+05:30');
const minutes = (m: number) => new Date(now.getTime() - m * 60_000).toISOString();
const hours = (h: number) => new Date(now.getTime() - h * 3_600_000).toISOString();
const daysAgo = (d: number) => new Date(now.getTime() - d * 86_400_000).toISOString();
const daysAhead = (d: number) => new Date(now.getTime() + d * 86_400_000).toISOString();

// ────────────────────────────────────────────────────────────────────────────────
// USERS — donors, NGOs, volunteers, admin
// ────────────────────────────────────────────────────────────────────────────────

export const seedUsers: DemoUser[] = [
  // ───── DONORS (restaurants, hotels, individuals) ─────
  {
    id: 'user_donor_1',
    name: 'Priya Menon',
    email: 'priya@tajpalace.com',
    password: 'demo1234',
    role: 'donor',
    phone: '+91 98201 12345',
    avatarColor: 'from-emerald-500 to-teal-600',
    initials: 'PM',
    city: 'Jaipur',
    organization: 'Taj Palace Jaipur',
    joinedAt: daysAgo(420),
    rating: 4.9,
    location: { lat: 26.9124, lng: 75.7873 },
    address: {
      street: 'MI Road',
      area: 'C-Scheme',
      city: 'Jaipur',
      state: 'Rajasthan',
      postalCode: '302001',
    },
    stats: {
      totalDonations: 128,
      totalKgRescued: 1450,
      mealsProvided: 4350,
      co2Saved: 980,
      impactScore: 9420,
    },
    online: true,
    isActive: true,
  },
  {
    id: 'user_donor_2',
    name: 'Rohan Verma',
    email: 'rohan@spicegarden.in',
    password: 'demo1234',
    role: 'donor',
    phone: '+91 98112 65432',
    avatarColor: 'from-orange-500 to-red-600',
    initials: 'RV',
    city: 'Delhi',
    organization: 'Spice Garden Restaurant',
    joinedAt: daysAgo(310),
    rating: 4.7,
    location: { lat: 28.6139, lng: 77.2090 },
    address: {
      street: 'Hauz Khas Village',
      area: 'Hauz Khas',
      city: 'New Delhi',
      state: 'Delhi',
      postalCode: '110016',
    },
    stats: {
      totalDonations: 84,
      totalKgRescued: 920,
      mealsProvided: 2760,
      co2Saved: 612,
      impactScore: 7150,
    },
    online: true,
    isActive: true,
  },
  {
    id: 'user_donor_3',
    name: 'Anjali Reddy',
    email: 'anjali@biryanihouse.com',
    password: 'demo1234',
    role: 'donor',
    phone: '+91 99887 54321',
    avatarColor: 'from-purple-500 to-pink-600',
    initials: 'AR',
    city: 'Bengaluru',
    organization: 'Hyderabad Biryani House',
    joinedAt: daysAgo(180),
    rating: 4.8,
    location: { lat: 12.9716, lng: 77.5946 },
    address: {
      street: '100 Feet Road',
      area: 'Indiranagar',
      city: 'Bengaluru',
      state: 'Karnataka',
      postalCode: '560038',
    },
    stats: {
      totalDonations: 56,
      totalKgRescued: 720,
      mealsProvided: 2160,
      co2Saved: 450,
      impactScore: 5680,
    },
    online: false,
    isActive: true,
  },
  {
    id: 'user_donor_4',
    name: 'Karan Shah',
    email: 'karan@gmail.com',
    password: 'demo1234',
    role: 'donor',
    phone: '+91 90080 11223',
    avatarColor: 'from-blue-500 to-indigo-600',
    initials: 'KS',
    city: 'Pune',
    organization: 'Individual Donor',
    joinedAt: daysAgo(95),
    rating: 4.6,
    location: { lat: 18.5204, lng: 73.8567 },
    address: {
      street: 'Koregaon Park Lane 5',
      area: 'Koregaon Park',
      city: 'Pune',
      state: 'Maharashtra',
      postalCode: '411001',
    },
    stats: {
      totalDonations: 22,
      totalKgRescued: 165,
      mealsProvided: 495,
      co2Saved: 110,
      impactScore: 1540,
    },
    online: true,
    isActive: true,
  },

  // ───── NGOs ─────
  {
    id: 'user_ngo_1',
    name: 'Jaipur Food Bank',
    email: 'contact@jaipurfoodbank.org',
    password: 'demo1234',
    role: 'ngo',
    phone: '+91 22 6655 1234',
    avatarColor: 'from-green-500 to-emerald-600',
    initials: 'MFB',
    city: 'Jaipur',
    organization: 'Jaipur Food Bank',
    capacity: 1200,
    servingAreas: ['Mansarovar', 'Malviya Nagar', 'Durgapura', 'Sodala'],
    joinedAt: daysAgo(820),
    rating: 4.9,
    location: { lat: 26.8760, lng: 75.7523 },
    address: {
      street: 'Madhyam Marg',
      area: 'Mansarovar',
      city: 'Jaipur',
      state: 'Rajasthan',
      postalCode: '302020',
    },
    stats: {
      totalDonations: 4220,
      totalKgRescued: 38400,
      mealsProvided: 115200,
      co2Saved: 24600,
      impactScore: 248000,
    },
    online: true,
    isActive: true,
  },
  {
    id: 'user_ngo_2',
    name: 'Annamrita Foundation',
    email: 'help@annamrita.org',
    password: 'demo1234',
    role: 'ngo',
    phone: '+91 22 4488 7766',
    avatarColor: 'from-amber-500 to-orange-600',
    initials: 'AF',
    city: 'Jaipur',
    organization: 'Annamrita Foundation',
    capacity: 2500,
    servingAreas: ['Jagatpura', 'Pratap Nagar', 'Sanganer', 'Tonk Road'],
    joinedAt: daysAgo(990),
    rating: 4.8,
    location: { lat: 26.8467, lng: 75.8256 },
    address: {
      street: 'Goner Road',
      area: 'Jagatpura',
      city: 'Jaipur',
      state: 'Rajasthan',
      postalCode: '302017',
    },
    stats: {
      totalDonations: 5680,
      totalKgRescued: 52100,
      mealsProvided: 156300,
      co2Saved: 33400,
      impactScore: 312000,
    },
    online: true,
    isActive: true,
  },
  {
    id: 'user_ngo_3',
    name: 'Robin Hood Army Delhi',
    email: 'delhi@robinhoodarmy.com',
    password: 'demo1234',
    role: 'ngo',
    phone: '+91 11 4567 8899',
    avatarColor: 'from-rose-500 to-red-600',
    initials: 'RHA',
    city: 'Delhi',
    organization: 'Robin Hood Army',
    capacity: 1800,
    servingAreas: ['Connaught Place', 'Karol Bagh', 'Old Delhi'],
    joinedAt: daysAgo(1100),
    rating: 4.9,
    location: { lat: 28.6304, lng: 77.2177 },
    address: {
      street: 'Connaught Circle',
      area: 'Connaught Place',
      city: 'New Delhi',
      state: 'Delhi',
      postalCode: '110001',
    },
    stats: {
      totalDonations: 6420,
      totalKgRescued: 64800,
      mealsProvided: 194400,
      co2Saved: 41500,
      impactScore: 387000,
    },
    online: true,
    isActive: true,
  },
  {
    id: 'user_ngo_4',
    name: 'Akshaya Patra Bengaluru',
    email: 'blr@akshayapatra.org',
    password: 'demo1234',
    role: 'ngo',
    phone: '+91 80 3015 1234',
    avatarColor: 'from-yellow-500 to-amber-600',
    initials: 'AP',
    city: 'Bengaluru',
    organization: 'Akshaya Patra Foundation',
    capacity: 3500,
    servingAreas: ['Koramangala', 'Indiranagar', 'Whitefield', 'HSR Layout'],
    joinedAt: daysAgo(1500),
    rating: 5.0,
    location: { lat: 12.9352, lng: 77.6245 },
    address: {
      street: '5th Block',
      area: 'Koramangala',
      city: 'Bengaluru',
      state: 'Karnataka',
      postalCode: '560095',
    },
    stats: {
      totalDonations: 8240,
      totalKgRescued: 92300,
      mealsProvided: 276900,
      co2Saved: 59100,
      impactScore: 552000,
    },
    online: false,
    isActive: true,
  },

  // ───── VOLUNTEERS ─────
  {
    id: 'user_vol_1',
    name: 'Amit Kumar',
    email: 'amit.k@volunteer.com',
    password: 'demo1234',
    role: 'volunteer',
    phone: '+91 98765 43210',
    avatarColor: 'from-cyan-500 to-blue-600',
    initials: 'AK',
    city: 'Jaipur',
    vehicleType: 'motorcycle',
    joinedAt: daysAgo(220),
    rating: 4.9,
    location: { lat: 26.8760, lng: 75.7523 },
    address: {
      street: 'Madhyam Marg',
      area: 'Mansarovar',
      city: 'Jaipur',
      state: 'Rajasthan',
      postalCode: '302020',
    },
    stats: {
      totalDonations: 312,
      totalKgRescued: 0,
      mealsProvided: 9360,
      co2Saved: 0,
      impactScore: 6200,
    },
    online: true,
    isActive: true,
  },
  {
    id: 'user_vol_2',
    name: 'Priya Sharma',
    email: 'priya.s@volunteer.com',
    password: 'demo1234',
    role: 'volunteer',
    phone: '+91 98765 43211',
    avatarColor: 'from-pink-500 to-rose-600',
    initials: 'PS',
    city: 'Jaipur',
    vehicleType: 'car',
    joinedAt: daysAgo(180),
    rating: 4.8,
    location: { lat: 26.8467, lng: 75.8256 },
    address: {
      street: 'Tonk Road',
      area: 'Pratap Nagar',
      city: 'Jaipur',
      state: 'Rajasthan',
      postalCode: '302033',
    },
    stats: {
      totalDonations: 248,
      totalKgRescued: 0,
      mealsProvided: 7440,
      co2Saved: 0,
      impactScore: 4960,
    },
    online: true,
    isActive: true,
  },
  {
    id: 'user_vol_3',
    name: 'Ravi Singh',
    email: 'ravi.s@volunteer.com',
    password: 'demo1234',
    role: 'volunteer',
    phone: '+91 98765 43212',
    avatarColor: 'from-violet-500 to-purple-600',
    initials: 'RS',
    city: 'Delhi',
    vehicleType: 'van',
    joinedAt: daysAgo(140),
    rating: 4.7,
    location: { lat: 28.6448, lng: 77.2167 },
    address: {
      street: 'Karol Bagh Main Road',
      area: 'Karol Bagh',
      city: 'New Delhi',
      state: 'Delhi',
      postalCode: '110005',
    },
    stats: {
      totalDonations: 184,
      totalKgRescued: 0,
      mealsProvided: 5520,
      co2Saved: 0,
      impactScore: 3680,
    },
    online: true,
    isActive: true,
  },
  {
    id: 'user_vol_4',
    name: 'Neha Iyer',
    email: 'neha.i@volunteer.com',
    password: 'demo1234',
    role: 'volunteer',
    phone: '+91 98765 43213',
    avatarColor: 'from-emerald-500 to-green-600',
    initials: 'NI',
    city: 'Bengaluru',
    vehicleType: 'bicycle',
    joinedAt: daysAgo(60),
    rating: 4.9,
    location: { lat: 12.9716, lng: 77.6412 },
    address: {
      street: '12th Main',
      area: 'Indiranagar',
      city: 'Bengaluru',
      state: 'Karnataka',
      postalCode: '560038',
    },
    stats: {
      totalDonations: 78,
      totalKgRescued: 0,
      mealsProvided: 2340,
      co2Saved: 0,
      impactScore: 1560,
    },
    online: false,
    isActive: true,
  },

  // ───── ADMIN ─────
  {
    id: 'user_admin_1',
    name: 'Aarav Sharma',
    email: 'admin@mealrelay.org',
    password: 'admin1234',
    role: 'admin',
    phone: '+91 98000 00001',
    avatarColor: 'from-slate-700 to-slate-900',
    initials: 'AS',
    city: 'Jaipur',
    organization: 'Meal Relay HQ',
    joinedAt: daysAgo(1800),
    rating: 5.0,
    location: { lat: 26.9124, lng: 75.7873 },
    address: {
      street: 'Mirza Ismail Road',
      area: 'C-Scheme',
      city: 'Jaipur',
      state: 'Rajasthan',
      postalCode: '302001',
    },
    stats: {
      totalDonations: 0,
      totalKgRescued: 0,
      mealsProvided: 0,
      co2Saved: 0,
      impactScore: 0,
    },
    online: true,
    isActive: true,
  },
];

// ────────────────────────────────────────────────────────────────────────────────
// DONATIONS — stable mock catalog
// ────────────────────────────────────────────────────────────────────────────────

export const seedDonations: Donation[] = [
  {
    id: 'don_001',
    donorId: 'user_donor_1',
    ngoId: 'user_ngo_1',
    volunteerId: 'user_vol_1',
    title: 'Wedding Buffet Surplus',
    description:
      'Veg biryani, paneer butter masala, dal makhani and naan from a 200-pax wedding reception.',
    category: 'cooked-meals',
    cuisine: 'Indian',
    quantityKg: 32,
    servings: 96,
    isVegetarian: true,
    allergens: ['dairy', 'gluten'],
    imageUrl:
      'https://images.pexels.com/photos/1410235/pexels-photo-1410235.jpeg?auto=compress&cs=tinysrgb&w=800',
    pickupAddress: seedUsers[0].address,
    pickupLocation: seedUsers[0].location,
    dropoffLocation: seedUsers[4].location,
    pickupWindowStart: minutes(-30),
    pickupWindowEnd: minutes(-90),
    expiresAt: hours(-4),
    status: 'in-transit',
    priority: 'high',
    notes: 'Please bring insulated containers.',
    createdAt: minutes(45),
    updatedAt: minutes(10),
    freshness: 92,
    estimatedMeals: 96,
    co2SavedKg: 22,
    beneficiaries: 96,
    trackingPath: [
      { lat: 26.9124, lng: 75.7873 },
      { lat: 26.9050, lng: 75.7790 },
      { lat: 26.8950, lng: 75.7680 },
      { lat: 26.8850, lng: 75.7580 },
      { lat: 26.8760, lng: 75.7523 },
    ],
  },
  {
    id: 'don_002',
    donorId: 'user_donor_2',
    ngoId: 'user_ngo_3',
    volunteerId: 'user_vol_3',
    title: 'Fresh Naan & Curry Pack',
    description:
      'Tandoori naan, dal tadka and mixed vegetable curry from today\'s lunch service.',
    category: 'cooked-meals',
    cuisine: 'Indian',
    quantityKg: 18,
    servings: 54,
    isVegetarian: true,
    allergens: ['gluten'],
    imageUrl:
      'https://images.pexels.com/photos/2474661/pexels-photo-2474661.jpeg?auto=compress&cs=tinysrgb&w=800',
    pickupAddress: seedUsers[1].address,
    pickupLocation: seedUsers[1].location,
    dropoffLocation: seedUsers[6].location,
    pickupWindowStart: minutes(-15),
    pickupWindowEnd: minutes(-75),
    expiresAt: hours(-3),
    status: 'picked-up',
    priority: 'medium',
    createdAt: hours(2),
    updatedAt: minutes(20),
    freshness: 88,
    estimatedMeals: 54,
    co2SavedKg: 12,
    beneficiaries: 54,
    trackingPath: [
      { lat: 28.6139, lng: 77.2090 },
      { lat: 28.6200, lng: 77.2120 },
      { lat: 28.6304, lng: 77.2177 },
    ],
  },
  {
    id: 'don_003',
    donorId: 'user_donor_3',
    ngoId: 'user_ngo_4',
    volunteerId: 'user_vol_4',
    title: 'Hyderabad Dum Biryani — 25 Plates',
    description:
      'Aromatic dum biryani with raita and salan, prepared this morning.',
    category: 'cooked-meals',
    cuisine: 'Indian',
    quantityKg: 25,
    servings: 75,
    isVegetarian: false,
    allergens: ['dairy'],
    imageUrl:
      'https://images.pexels.com/photos/1624487/pexels-photo-1624487.jpeg?auto=compress&cs=tinysrgb&w=800',
    pickupAddress: seedUsers[2].address,
    pickupLocation: seedUsers[2].location,
    dropoffLocation: seedUsers[7].location,
    pickupWindowStart: minutes(15),
    pickupWindowEnd: minutes(75),
    expiresAt: hours(-2),
    status: 'assigned',
    priority: 'urgent',
    createdAt: minutes(60),
    updatedAt: minutes(5),
    freshness: 95,
    estimatedMeals: 75,
    co2SavedKg: 18,
    beneficiaries: 75,
  },
  {
    id: 'don_004',
    donorId: 'user_donor_1',
    title: 'Continental Breakfast Spread',
    description:
      'Croissants, pancakes, fresh fruits, juices, and toast leftover from buffet.',
    category: 'baked-goods',
    cuisine: 'Continental',
    quantityKg: 14,
    servings: 28,
    isVegetarian: true,
    allergens: ['gluten', 'dairy', 'eggs'],
    imageUrl:
      'https://images.pexels.com/photos/3631165/pexels-photo-3631165.jpeg?auto=compress&cs=tinysrgb&w=800',
    pickupAddress: seedUsers[0].address,
    pickupLocation: seedUsers[0].location,
    pickupWindowStart: minutes(30),
    pickupWindowEnd: minutes(90),
    expiresAt: hours(-2),
    status: 'pending',
    priority: 'high',
    createdAt: minutes(15),
    updatedAt: minutes(15),
    freshness: 90,
    estimatedMeals: 28,
    co2SavedKg: 9,
  },
  {
    id: 'don_005',
    donorId: 'user_donor_4',
    title: 'Home-cooked Sambar Rice',
    description:
      'Fresh sambar rice prepared for a family gathering. Stored in clean containers.',
    category: 'cooked-meals',
    cuisine: 'Indian',
    quantityKg: 8,
    servings: 24,
    isVegetarian: true,
    allergens: [],
    imageUrl:
      'https://images.pexels.com/photos/9609839/pexels-photo-9609839.jpeg?auto=compress&cs=tinysrgb&w=800',
    pickupAddress: seedUsers[3].address,
    pickupLocation: seedUsers[3].location,
    pickupWindowStart: minutes(45),
    pickupWindowEnd: minutes(120),
    expiresAt: hours(-1),
    status: 'pending',
    priority: 'medium',
    createdAt: minutes(8),
    updatedAt: minutes(8),
    freshness: 96,
    estimatedMeals: 24,
    co2SavedKg: 5,
  },
  {
    id: 'don_006',
    donorId: 'user_donor_2',
    ngoId: 'user_ngo_3',
    volunteerId: 'user_vol_3',
    title: 'Fresh Vegetables — End of Day',
    description: 'Mixed seasonal vegetables — tomatoes, capsicum, onions, carrots, leafy greens.',
    category: 'fresh-produce',
    cuisine: 'Indian',
    quantityKg: 22,
    servings: 44,
    isVegetarian: true,
    allergens: [],
    imageUrl:
      'https://images.pexels.com/photos/1300972/pexels-photo-1300972.jpeg?auto=compress&cs=tinysrgb&w=800',
    pickupAddress: seedUsers[1].address,
    pickupLocation: seedUsers[1].location,
    pickupWindowStart: hours(-5),
    pickupWindowEnd: hours(-3),
    expiresAt: hours(36),
    status: 'delivered',
    priority: 'medium',
    createdAt: hours(8),
    updatedAt: hours(2),
    freshness: 85,
    estimatedMeals: 44,
    co2SavedKg: 8,
    beneficiaries: 44,
  },
  {
    id: 'don_007',
    donorId: 'user_donor_3',
    ngoId: 'user_ngo_4',
    volunteerId: 'user_vol_4',
    title: 'Birthday Party Cake & Sweets',
    description: 'Untouched cake slices, gulab jamun and rasgulla from kids party.',
    category: 'desserts',
    cuisine: 'Indian',
    quantityKg: 6,
    servings: 30,
    isVegetarian: true,
    allergens: ['dairy', 'eggs', 'gluten', 'nuts'],
    imageUrl:
      'https://images.pexels.com/photos/291528/pexels-photo-291528.jpeg?auto=compress&cs=tinysrgb&w=800',
    pickupAddress: seedUsers[2].address,
    pickupLocation: seedUsers[2].location,
    pickupWindowStart: hours(-9),
    pickupWindowEnd: hours(-7),
    expiresAt: hours(12),
    status: 'delivered',
    priority: 'low',
    createdAt: hours(12),
    updatedAt: hours(6),
    freshness: 80,
    estimatedMeals: 30,
    co2SavedKg: 4,
    beneficiaries: 30,
  },
  {
    id: 'don_008',
    donorId: 'user_donor_1',
    ngoId: 'user_ngo_2',
    volunteerId: 'user_vol_2',
    title: 'Conference Lunch Boxes',
    description:
      'Sealed lunch boxes — steamed rice, paneer tikka masala, chapati, sweet.',
    category: 'cooked-meals',
    cuisine: 'Indian',
    quantityKg: 40,
    servings: 80,
    isVegetarian: true,
    allergens: ['dairy', 'gluten'],
    imageUrl:
      'https://images.pexels.com/photos/4198015/pexels-photo-4198015.jpeg?auto=compress&cs=tinysrgb&w=800',
    pickupAddress: seedUsers[0].address,
    pickupLocation: seedUsers[0].location,
    pickupWindowStart: hours(-25),
    pickupWindowEnd: hours(-23),
    expiresAt: hours(-12),
    status: 'delivered',
    priority: 'high',
    createdAt: daysAgo(1),
    updatedAt: hours(20),
    freshness: 90,
    estimatedMeals: 80,
    co2SavedKg: 25,
    beneficiaries: 80,
  },
  {
    id: 'don_009',
    donorId: 'user_donor_4',
    ngoId: 'user_ngo_1',
    volunteerId: 'user_vol_1',
    title: 'Bakery End-of-day Breads',
    description: 'Loaves, buns and pastries from a local bakery before closing.',
    category: 'baked-goods',
    cuisine: 'Continental',
    quantityKg: 12,
    servings: 36,
    isVegetarian: true,
    allergens: ['gluten', 'dairy'],
    imageUrl:
      'https://images.pexels.com/photos/1775043/pexels-photo-1775043.jpeg?auto=compress&cs=tinysrgb&w=800',
    pickupAddress: seedUsers[3].address,
    pickupLocation: seedUsers[3].location,
    pickupWindowStart: daysAgo(2),
    pickupWindowEnd: daysAgo(2),
    expiresAt: daysAgo(1),
    status: 'delivered',
    priority: 'medium',
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
    freshness: 78,
    estimatedMeals: 36,
    co2SavedKg: 7,
    beneficiaries: 36,
  },
  {
    id: 'don_010',
    donorId: 'user_donor_2',
    ngoId: 'user_ngo_3',
    title: 'Packaged Snacks — Office Surplus',
    description:
      'Sealed packets of biscuits, namkeen, chips and juice boxes from corporate event.',
    category: 'packaged-food',
    cuisine: 'Other',
    quantityKg: 15,
    servings: 60,
    isVegetarian: true,
    allergens: ['gluten'],
    imageUrl:
      'https://images.pexels.com/photos/4109743/pexels-photo-4109743.jpeg?auto=compress&cs=tinysrgb&w=800',
    pickupAddress: seedUsers[1].address,
    pickupLocation: seedUsers[1].location,
    pickupWindowStart: minutes(120),
    pickupWindowEnd: minutes(240),
    expiresAt: daysAhead(60),
    status: 'accepted',
    priority: 'low',
    createdAt: minutes(40),
    updatedAt: minutes(20),
    freshness: 100,
    estimatedMeals: 60,
    co2SavedKg: 6,
  },
];

// ────────────────────────────────────────────────────────────────────────────────
// CHAT ROOMS + MESSAGES
// ────────────────────────────────────────────────────────────────────────────────

export const seedChatRooms: ChatRoom[] = [
  {
    id: 'room_1',
    name: 'Jaipur Food Bank · Wedding Buffet',
    type: 'group',
    donationId: 'don_001',
    participantIds: ['user_donor_1', 'user_ngo_1', 'user_vol_1'],
    unreadCount: 2,
    pinned: true,
  },
  {
    id: 'room_2',
    name: 'Robin Hood Army · Naan & Curry',
    type: 'group',
    donationId: 'don_002',
    participantIds: ['user_donor_2', 'user_ngo_3', 'user_vol_3'],
    unreadCount: 0,
  },
  {
    id: 'room_3',
    name: 'Akshaya Patra · Biryani Pickup',
    type: 'group',
    donationId: 'don_003',
    participantIds: ['user_donor_3', 'user_ngo_4', 'user_vol_4'],
    unreadCount: 1,
  },
  {
    id: 'room_4',
    name: 'Volunteer Coordination — Jaipur',
    type: 'group',
    participantIds: ['user_vol_1', 'user_vol_2', 'user_ngo_1', 'user_ngo_2'],
    unreadCount: 0,
  },
  {
    id: 'room_5',
    name: 'Support · Meal Relay',
    type: 'support',
    participantIds: ['user_admin_1', 'user_donor_1', 'user_donor_2'],
    unreadCount: 0,
  },
];

export const seedMessages: ChatMessage[] = [
  // Room 1 — Wedding buffet
  {
    id: 'm_1_1',
    roomId: 'room_1',
    senderId: 'user_donor_1',
    senderName: 'Priya Menon',
    senderRole: 'donor',
    content: 'Hi team — we have 32 kg of veg biryani and curries from a wedding tonight.',
    type: 'text',
    createdAt: minutes(50),
    read: true,
  },
  {
    id: 'm_1_2',
    roomId: 'room_1',
    senderId: 'user_ngo_1',
    senderName: 'Jaipur Food Bank',
    senderRole: 'ngo',
    content: 'Confirmed — assigning Amit Kumar for pickup. He can be there in 15 minutes.',
    type: 'text',
    createdAt: minutes(48),
    read: true,
  },
  {
    id: 'm_1_3',
    roomId: 'room_1',
    senderId: 'user_vol_1',
    senderName: 'Amit Kumar',
    senderRole: 'volunteer',
    content: 'On my way! ETA 12 minutes. Bringing 4 insulated containers.',
    type: 'text',
    createdAt: minutes(40),
    read: true,
  },
  {
    id: 'm_1_4',
    roomId: 'room_1',
    senderId: 'user_donor_1',
    senderName: 'Priya Menon',
    senderRole: 'donor',
    content: 'Perfect — please come to the service entrance at the back.',
    type: 'text',
    createdAt: minutes(35),
    read: true,
  },
  {
    id: 'm_1_5',
    roomId: 'room_1',
    senderId: 'user_vol_1',
    senderName: 'Amit Kumar',
    senderRole: 'volunteer',
    content: 'Picked up! Heading to the Mansarovar center now.',
    type: 'text',
    createdAt: minutes(15),
    read: false,
  },
  {
    id: 'm_1_6',
    roomId: 'room_1',
    senderId: 'user_ngo_1',
    senderName: 'Jaipur Food Bank',
    senderRole: 'ngo',
    content: '🙏 Thank you Priya — this will feed 96 people tonight.',
    type: 'text',
    createdAt: minutes(8),
    read: false,
  },

  // Room 2 — Robin Hood Army
  {
    id: 'm_2_1',
    roomId: 'room_2',
    senderId: 'user_donor_2',
    senderName: 'Rohan Verma',
    senderRole: 'donor',
    content: '18 kg of fresh naan, dal and curry ready for pickup.',
    type: 'text',
    createdAt: hours(2),
    read: true,
  },
  {
    id: 'm_2_2',
    roomId: 'room_2',
    senderId: 'user_ngo_3',
    senderName: 'Robin Hood Army Delhi',
    senderRole: 'ngo',
    content: 'Excellent — Ravi Singh will be there shortly.',
    type: 'text',
    createdAt: hours(2),
    read: true,
  },
  {
    id: 'm_2_3',
    roomId: 'room_2',
    senderId: 'user_vol_3',
    senderName: 'Ravi Singh',
    senderRole: 'volunteer',
    content: 'Picked up successfully — distributing at Connaught Place now.',
    type: 'text',
    createdAt: minutes(20),
    read: true,
  },

  // Room 3 — Biryani
  {
    id: 'm_3_1',
    roomId: 'room_3',
    senderId: 'user_donor_3',
    senderName: 'Anjali Reddy',
    senderRole: 'donor',
    content: '25 plates of fresh dum biryani ready. Time-sensitive — please pick up within an hour.',
    type: 'text',
    createdAt: minutes(60),
    read: true,
  },
  {
    id: 'm_3_2',
    roomId: 'room_3',
    senderId: 'user_ngo_4',
    senderName: 'Akshaya Patra Bengaluru',
    senderRole: 'ngo',
    content: 'Accepted! Neha is heading over with the cooler bag.',
    type: 'text',
    createdAt: minutes(55),
    read: true,
  },
  {
    id: 'm_3_3',
    roomId: 'room_3',
    senderId: 'user_vol_4',
    senderName: 'Neha Iyer',
    senderRole: 'volunteer',
    content: '🚲 On my way from Indiranagar — 18 minutes ETA.',
    type: 'text',
    createdAt: minutes(30),
    read: false,
  },

  // Room 4 — Coordination
  {
    id: 'm_4_1',
    roomId: 'room_4',
    senderId: 'user_ngo_1',
    senderName: 'Jaipur Food Bank',
    senderRole: 'ngo',
    content: 'Team — high donation volume expected this weekend due to festival.',
    type: 'text',
    createdAt: hours(5),
    read: true,
  },
  {
    id: 'm_4_2',
    roomId: 'room_4',
    senderId: 'user_vol_2',
    senderName: 'Priya Sharma',
    senderRole: 'volunteer',
    content: 'I can take 4 extra slots Sat/Sun. Vehicle: car.',
    type: 'text',
    createdAt: hours(4),
    read: true,
  },
  {
    id: 'm_4_3',
    roomId: 'room_4',
    senderId: 'user_vol_1',
    senderName: 'Amit Kumar',
    senderRole: 'volunteer',
    content: 'Same here — I can do all weekend evenings.',
    type: 'text',
    createdAt: hours(4),
    read: true,
  },

  // Room 5 — Support
  {
    id: 'm_5_1',
    roomId: 'room_5',
    senderId: 'user_admin_1',
    senderName: 'Meal Relay Support',
    senderRole: 'admin',
    content: 'Welcome to Meal Relay! 🎉 Reply here if you need anything.',
    type: 'text',
    createdAt: daysAgo(2),
    read: true,
  },
];

// Hydrate `lastMessage` on rooms
seedChatRooms.forEach((room) => {
  const msgs = seedMessages.filter((m) => m.roomId === room.id);
  room.lastMessage = msgs[msgs.length - 1];
});

// ────────────────────────────────────────────────────────────────────────────────
// NOTIFICATIONS + ACTIVITY
// ────────────────────────────────────────────────────────────────────────────────

export const seedNotifications: AppNotification[] = [
  {
    id: 'notif_1',
    userId: 'user_donor_1',
    type: 'donation_picked_up',
    title: 'Donation picked up',
    description: 'Amit Kumar picked up your wedding buffet surplus.',
    link: '/dashboard',
    read: false,
    createdAt: minutes(15),
    icon: 'truck',
  },
  {
    id: 'notif_2',
    userId: 'user_donor_1',
    type: 'message',
    title: 'New message',
    description: 'Jaipur Food Bank: Thank you Priya — this will feed 96 people tonight.',
    link: '/chat',
    read: false,
    createdAt: minutes(8),
    icon: 'message',
  },
  {
    id: 'notif_3',
    userId: 'user_donor_1',
    type: 'achievement',
    title: 'Achievement unlocked',
    description: 'You\'ve reached 100+ donations — Community Hero badge!',
    link: '/dashboard',
    read: true,
    createdAt: hours(12),
    icon: 'award',
  },
  {
    id: 'notif_4',
    userId: 'user_ngo_1',
    type: 'donation_created',
    title: 'New donation available',
    description: 'Continental breakfast spread (14 kg) at Taj Palace Jaipur.',
    link: '/ngo/dashboard',
    read: false,
    createdAt: minutes(15),
    icon: 'package',
  },
  {
    id: 'notif_5',
    userId: 'user_vol_1',
    type: 'donation_accepted',
    title: 'New pickup assigned',
    description: 'You\'ve been assigned to pickup #DON-001 at Taj Palace.',
    link: '/volunteer/dashboard',
    read: false,
    createdAt: minutes(45),
    icon: 'route',
  },
  {
    id: 'notif_6',
    userId: 'user_admin_1',
    type: 'system',
    title: 'System health',
    description: 'All services operational. 4 active deliveries in progress.',
    read: true,
    createdAt: hours(1),
    icon: 'shield',
  },
];

export const seedActivity: ActivityEvent[] = [
  {
    id: 'act_1',
    userId: 'user_donor_1',
    actor: 'Priya Menon',
    action: 'created',
    subject: 'Wedding Buffet Surplus',
    meta: { quantity: '32 kg', servings: 96 },
    createdAt: minutes(45),
  },
  {
    id: 'act_2',
    userId: 'user_ngo_1',
    actor: 'Jaipur Food Bank',
    action: 'accepted',
    subject: 'Wedding Buffet Surplus',
    createdAt: minutes(40),
  },
  {
    id: 'act_3',
    userId: 'user_vol_1',
    actor: 'Amit Kumar',
    action: 'picked up',
    subject: 'Wedding Buffet Surplus',
    createdAt: minutes(15),
  },
  {
    id: 'act_4',
    userId: 'user_donor_2',
    actor: 'Rohan Verma',
    action: 'created',
    subject: 'Fresh Naan & Curry Pack',
    meta: { quantity: '18 kg', servings: 54 },
    createdAt: hours(2),
  },
  {
    id: 'act_5',
    userId: 'user_ngo_4',
    actor: 'Akshaya Patra Bengaluru',
    action: 'distributed',
    subject: 'Birthday Party Sweets',
    meta: { beneficiaries: 30 },
    createdAt: hours(6),
  },
];
